spring:
  cloud:
    gateway:
      routes:
      - id: vet
        uri: lb://vets-service
        predicates:
          - Path=/api/vet/**
      - id: visit
        uri: lb://visits-service
        predicates:
          - Path=/api/visit/**
      - id: customer
        uri: lb://customers-service
        predicates:
          - Path=/api/customer/**
      - id: gateway
        uri: lb://api-gateway
        predicates:
          - Path=/api/gateway/**

server:
  compression:
    enabled: true
    mime-types: application/json,text/css,application/javascript
    min-response-size: 2048

# Internationalization
spring.messages.basename: messages/messages

eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-server:8761/eureka/